KVM: selftests: Fix build breakage in rseq_test.c due to KABI
make -C tools/testing/selftests/kvm
make: Entering directory '/blkvol/linux-uek/tools/testing/selftests/kvm'
make --no-builtin-rules ARCH=x86 -C ../../../.. headers_install
make[1]: Entering directory '/blkvol/linux-uek'
  INSTALL ./usr/include
make[1]: Leaving directory '/blkvol/linux-uek'
gcc -Wall -Wstrict-prototypes -Wuninitialized -O2 -g -std=gnu99 -fno-stack-protector -fno-PIE -I../../../../tools/include -I../../../../tools/arch/x86/include -I../../../../usr/include/ -Iinclude -I. -Iinclude/x86_64 -I..  -pthread  -no-pie   rseq_test.c /blkvol/linux-uek/tools/testing/selftests/kvm/libkvm.a  -o /blkvol/linux-uek/tools/testing/selftests/kvm/rseq_test
In file included from rseq_test.c:16:
../../../../usr/include/linux/rseq.h:112:9: error: expected specifier-qualifier-list before ‘UEK_KABI_REPLACE’
  112 |         UEK_KABI_REPLACE(
      |         ^~~~~~~~~~~~~~~~
make: *** [../lib.mk:146: /blkvol/linux-uek/tools/testing/selftests/kvm/rseq_test] Error 1
make: Leaving directory '/blkvol/linux-uek/tools/testing/selftests/kvm'

Fixing a KABI issue in the rseq code involved using the UEK_KABI_REPLACE macro.
This worked for the code in kernel/rseq.c but not for testing/selftests/kvm/
so explicitly include the uek_kabi.h header file so the definition can be picked up.

Orabug: 34325126

Fixes: 941b1d7993e1 ("rseq: Remove broken uapi field layout on 32-bit little endian")
Signed-off-by: Liam Merwick <liam.merwick@oracle.com>
Signed-off-by: Maciej S. Szmigiero <maciej.szmigiero@oracle.com>
Reviewed-by: Darren Kenny <darren.kenny@oracle.com>
(cherry picked from commit 403265c1f19dc1b1a7ac18b55c529d648c4d62e8)
Signed-off-by: Jack Vogel <jack.vogel@oracle.com>