Revert "KVM: x86: Fix wall clock writes in Xen shared_info not to mark page dirty"
kvm_gfn_to_pfn_cache_init is not defined, which is leading to
compilation error

arch/x86/kvm/xen.c:41:23: error: implicit declaration of function 'kvm_gfn_to_pfn_cache_init'

This reverts commit 75f03213882ce0f993ae6b2a64465e32631dd05a.

Orabug: 34929435

Signed-off-by: Vijayendra Suman <vijayendra.suman@oracle.com>
Reviewed-by: Jack Vogel <jack.vogel@oracle.com>