Revert "bpf: Allow reads from uninit stack"
This reverts commit ab10edc86d9fb94634ae79fa12ca56bc151b6113.

bpf selftest do not compile.
Commit "bpf: Allow reads from uninit stack" introduced the usage of '__failure',
without bringing the commit where this is defined.

Logs:

17242 progs/test_global_func10.c:24:17: error: expected parameter declarator
17243 __failure __msg("invalid indirect access to stack")
17244 ^
17245 progs/test_global_func10.c:24:17: error: expected ')'
17246 progs/test_global_func10.c:24:16: note: to match this '('
17247 __failure __msg("invalid indirect access to stack")
17248 ^
17249 progs/test_global_func10.c:24:52: error: expected ';' after top level declarator
17250 __failure __msg("invalid indirect access to stack")

Orabug: 36977604

Signed-off-by: Vijayendra Suman <vijayendra.suman@oracle.com>
Reviewed-by: Darren Kenny <darren.kenny@oracle.com>
Signed-off-by: Brian Maly <brian.maly@oracle.com>