uapi perf_event.h: Fixes perf compilation error
The perf tools failed to compile because the userspace API header file
includes uek_kabi.h. Mixing userspace and kernel space header files
will create more issues, let's manually expand the macro and
remove uek_kabi.h from the header file.

Steps to recreate the issue:

    cd <uek_tree>

    # The following step is needed to make sure the header file in tools
    # directory is in sync with the userspace API header.
    cp include/uapi/linux/perf_event.h tools/include/uapi/linux/perf_event.h

    # compiling perf
    make -C tools perf

    # error message
    In file included from util/parse-events.h:11,
                     from builtin-list.c:13:
    /home/<uek_tree>/tools/include/uapi/linux/perf_event.h:21:10: fatal
    error:
    linux/uek_kabi.h: No such file or directory
     #include <linux/uek_kabi.h>
              ^~~~~~~~~~~~~~~~~~
    compilation terminated.

The patch also update the tools/include/uapi/linux/perf_event.h to fix the
following warning message.

    Warning: Kernel ABI header at 'tools/include/uapi/linux/perf_event.h'
    differs from latest version at 'include/uapi/linux/perf_event.h'

Orabug: 35275813

Signed-off-by: Thomas Tai <thomas.tai@oracle.com>
Reviewed-by: Henry Willard <henry.willard@oracle.com>
Reviewed-by: Jack Vogel <jack.vogel@oracle.com>