Revert "KVM: x86/xen: Maintain valid mapping of Xen shared_info page"
kvm_gfn_to_pfn_cache_init is not defined, which is leading to
compilation error

arch/x86/kvm/xen.c:41:23: error: implicit declaration of function 'kvm_gfn_to_pfn_cache_init'

This reverts commit 9cccc48491db9bc95175f18fc9fcc29e6887202a.

Orabug: 34929435

Signed-off-by: Vijayendra Suman <vijayendra.suman@oracle.com>
Reviewed-by: Jack Vogel <jack.vogel@oracle.com>