i2c: thunderx: missing struct pci_dev definition in mips build
Build error on mips:
  CC      drivers/i2c/busses/i2c-octeon-platdrv.o
In file included from drivers/i2c/busses/i2c-octeon-platdrv.c:27:0:
drivers/i2c/busses/i2c-octeon-core.h: In function ‘octeon_i2c_is_otx2’:
drivers/i2c/busses/i2c-octeon-core.h:223:21: error: dereferencing pointer to incomplete type ‘struct pci_dev’
  u32 chip_id = (pdev->subsystem_device >> 12) & 0xF;
                     ^~
Fixes: 4ebcb6a900e7 ("drivers: i2c: thunderx: octeontx2 clock divisor logic changes")

Orabug: 30483967

Signed-off-by: Dave Kleikamp <dave.kleikamp@oracle.com>
Reviewed-by: Tom Saeger <tom.saeger@oracle.com>