wireguard: selftests: initalize ipv6 members to NULL to squelch clang warning
commit 4fed818ef54b08d4b29200e416cce65546ad5312 upstream.

Without setting these to NULL, clang complains in certain
configurations that have CONFIG_IPV6=n:

In file included from drivers/net/wireguard/ratelimiter.c:223:
drivers/net/wireguard/selftest/ratelimiter.c:173:34: error: variable 'skb6' is uninitialized when used here [-Werror,-Wuninitialized]
                ret = timings_test(skb4, hdr4, skb6, hdr6, &test_count);
                                               ^~~~
drivers/net/wireguard/selftest/ratelimiter.c:123:29: note: initialize the variable 'skb6' to silence this warning
        struct sk_buff *skb4, *skb6;
                                   ^
                                    = NULL
drivers/net/wireguard/selftest/ratelimiter.c:173:40: error: variable 'hdr6' is uninitialized when used here [-Werror,-Wuninitialized]
                ret = timings_test(skb4, hdr4, skb6, hdr6, &test_count);
                                                     ^~~~
drivers/net/wireguard/selftest/ratelimiter.c:125:22: note: initialize the variable 'hdr6' to silence this warning
        struct ipv6hdr *hdr6;
                            ^

We silence this warning by setting the variables to NULL as the warning
suggests.

Reported-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Jason A. Donenfeld <Jason@zx2c4.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Jason A. Donenfeld <Jason@zx2c4.com>

Orabug: 32013736

(cherry picked from commit 4fed818ef54b08d4b29200e416cce65546ad5312)
cherry-pick-repo=https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/
unmodified-from-upstream: 4fed818ef54b08d4b29200e416cce65546ad5312

Signed-off-by: William Kucharski <william.kucharski@oracle.com>
Reviewed-by: Sharon Liu <sharon.s.liu@oracle.com>