net/mlx5: Lag, Make mlx5_lag_is_multipath() be static inline
Fix "no previous prototype" W=1 warnings when CONFIG_MLX5_CORE_EN is not set:

  drivers/net/ethernet/mellanox/mlx5/core/lag_mp.h:34:6: error: no previous prototype for ‘mlx5_lag_is_multipath’ [-Werror=missing-prototypes]
     34 | bool mlx5_lag_is_multipath(struct mlx5_core_dev *dev) { return false; }
        |      ^~~~~~~~~~~~~~~~~~~~~

Fixes: 14fe2471c628 ("net/mlx5: Lag, change multipath and bonding to be mutually exclusive")
Signed-off-by: Maor Dickman <maord@nvidia.com>

Orabug: 36014945

(cherry picked from commit 8ca9caee851c444810b70d9c167e7321f3ff68f8)
cherry-pick-repo=kernel/git/torvalds/linux.git

Conflicts:
	drivers/net/ethernet/mellanox/mlx5/core/lag/mp.h

Apply the fix to drivers/net/ethernet/mellanox/mlx5/core/lag_mp.h
instead, since the file restructuring code is missing.

Signed-off-by: Mikhael Goikhman <migo@nvidia.com>
Signed-off-by: Qing Huang <qing.huang@oracle.com>
Reviewed-by: Sharath Srinivasan <sharath.srinivasan@oracle.com>
Signed-off-by: Alok Tiwari <alok.a.tiwari@oracle.com>