net/mlx5e: Fix build error in fec_set_block_stats()
Build bot reports:

drivers/net/ethernet/mellanox/mlx5/core/en_stats.c: In function 'fec_set_block_stats':
drivers/net/ethernet/mellanox/mlx5/core/en_stats.c:1235:48: error: 'outl' undeclared (first use in this function); did you mean 'out'?
    1235 |         if (mlx5_core_access_reg(mdev, in, sz, outl, sz, MLX5_REG_PPCNT, 0, 0))
         |                                                ^~~~
         |                                                out

Reported-by: kernel test robot <lkp@intel.com>
Suggested-by: Leon Romanovsky <leon@kernel.org>
Signed-off-by: Jakub Kicinski <kuba@kernel.org>
Link: https://lore.kernel.org/r/20220109213321.2292830-1-kuba@kernel.org
Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Orabug: 34481188

(cherry picked from commit 342402c426902c59491b43d3056a1039e5ca02db)
cherry-pick-repo=kernel/git/torvalds/linux.git
unmodified-from-upstream: 342402c426902c59491b43d3056a1039e5ca02db

Signed-off-by: Mikhael Goikhman <migo@nvidia.com>
Signed-off-by: Qing Huang <qing.huang@oracle.com>
Reviewed-by: William Kucharski <william.kucharski@oracle.com>
Reviewed-by: Devesh Sharma <devesh.s.sharma@oracle.com>
(cherry picked from commit 77246b35d7f7be22e669d4901b80538e16aa04d5)
Signed-off-by: Jack Vogel <jack.vogel@oracle.com>