Revert "selftests: mm: fix map_hugetlb failure on 64K page size systems"
This reverts commit 9233163126e30c2cf60885485b53acbf510158b7.

Orabug: 36584568

map_hugetlb.c:18:10: fatal error: vm_util.h: No such file or directory
   18 | #include "vm_util.h"
      |          ^~~~~~~~~~~
compilation terminated.

vm_util.h is not present in 5.4.y, as commit:642bc52aed9c ("selftests:
vm: bring common functions to a new file") is not present in stable
kernels <=6.1.y

Signed-off-by: Harshit Mogalapalli <harshit.m.mogalapalli@oracle.com>
Reviewed-by: Sherry Yang <sherry.yang@oracle.com>
Signed-off-by: Sherry Yang <sherry.yang@oracle.com>