scsi: mptfusion: Add bounds check in mptctl_hp_targetinfo()
My static checker complains about an out of bounds read:

    drivers/message/fusion/mptctl.c:2786 mptctl_hp_targetinfo()
    error: buffer overflow 'hd->sel_timeout' 255 <= u32max.

It's true that we probably should have a bounds check here.

Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
Reviewed-by: Johannes Thumshirn <jthumshirn@suse.de>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
(cherry picked from commit a7043e9529f3c367cc4d82997e00be034cbe57ca)

Orabug: 31350941
CVE: CVE-2020-12652

Signed-off-by: Vijayendra Suman <vijayendra.suman@oracle.com>
Reviewed-by: John Donnelly  <john.p.donnelly@oracle.com>
Signed-off-by: Brian Maly <brian.maly@oracle.com>