vmscan: fix build warning caused by commit 44b0e03f8ab1
Commit 44b0e03f8ab1 ("vmscan: Support multiple kswapd threads per node")
introduced the following warning:

In file included from mm/vmscan.c:43:0:
mm/vmscan.c: In function 'kswapd_run':
./include/linux/kthread.h:45:9: warning: too many arguments for format [-Wformat-extra-args]
  struct task_struct *__k         \
         ^
mm/vmscan.c:3814:27: note: in expansion of macro 'kthread_run'
   kswapd_list[nid][hid] = kthread_run(kswapd, pgdat,

This not only created a build warning but also introduced the
possibility of duplicate kswapd thread names when more than one
kswapd thread per node is started. Fix this by adding the missing
format specifier for thread id.

Orabug: 27951638

Signed-off-by: Khalid Aziz <khalid.aziz@oracle.com>
Reviewed-by: Victor Erminpour <victor.erminpour@oracle.com>
Reviewed-by: Tom Saeger <tom.saeger@oracle.com>