EDAC: Octeon: Fix compile error by replacing sdei_init() with acpi_sdei_init()
Commit 812a9e75f35c firmware: SDEI: Allow sdei initialization without ACPI_APEI_GHES
sdei_init was moved into acpi_ghes_init instead of being a standalone initcall

+ make -s ARCH=arm64 -j16 Image modules
drivers/edac/octeontx_edac.c: In function 'octeontx_edac_init':
drivers/edac/octeontx_edac.c:1216:9: error: implicit declaration of function 'sdei_init';

replace sdei_init() with acpi_sdei_init()

Orabug: 38294908

Signed-off-by: Vijayendra Suman <vijayendra.suman@oracle.com>
Reviewed-by: Dave Kleikamp <dave.kleikamp@oracle.com>
Signed-off-by: Vijayendra Suman <vijayendra.suman@oracle.com>