cpu/speculation: Add prototype for cpu_show_srbds()
0-day is not happy that there is no prototype for cpu_show_srbds():

  drivers/base/cpu.c:565:16: error: no previous prototype for 'cpu_show_srbds'

Fixes: 7e5b3c267d25 ("x86/speculation: Add Special Register Buffer Data Sampling (SRBDS) mitigation")
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Borislav Petkov <bp@suse.de>
Link: https://lkml.kernel.org/r/20200617141410.93338-1-linux@roeck-us.net
(cherry picked from commit 2accfa69050c2a0d6fc6106f609208b3e9622b26)
Signed-off-by: Sherry Yang <sherry.yang@oracle.com>

Conflicts:
	include/linux/cpu.h