mlx5: fix psample_sample_packet link error
When PSAMPLE is a loadable module, built-in drivers cannot use it:

aarch64-linux-ld: drivers/net/ethernet/mellanox/mlx5/core/en/tc/sample.o: in function `mlx5e_tc_sample_skb':
sample.c:(.text+0xd68): undefined reference to `psample_sample_packet'

Add the same dependency here that is used for MLXSW

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>

Orabug: 34481188

(cherry picked from commit 7a7dd5114f53885419ef67c530e961d7ceaec15a)
cherry-pick-repo=kernel/git/torvalds/linux.git
unmodified-from-upstream: 7a7dd5114f53885419ef67c530e961d7ceaec15a

Signed-off-by: Mikhael Goikhman <migo@nvidia.com>
Signed-off-by: Qing Huang <qing.huang@oracle.com>
Reviewed-by: William Kucharski <william.kucharski@oracle.com>
Reviewed-by: Devesh Sharma <devesh.s.sharma@oracle.com>
(cherry picked from commit 8f4fb2c9e74ea8491dcc3438b5a3a130b1448857)
Signed-off-by: Jack Vogel <jack.vogel@oracle.com>