e1000e: Need to include vmalloc.h
Otherwise (on sparc64):

drivers/net/e1000e/ethtool.c:657:3: error: implicit declaration of function 'vmalloc' [-Werror=implicit-function-declaration]

(cherry picked from commit c85c21ad1fe18daf26bfe8684df974d88cec50b7)
Signed-off-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Joe Jin <joe.jin@oracle.com>