ACPI: APEI: EINJ: Refactor available_error_type_show()
Move error type descriptions into an array and loop over error types
to improve readability and maintainability.

Replace seq_printf() with seq_puts() as recommended by checkpatch.pl.

Signed-off-by: Jay Lu <jaylu102@amd.com>
Co-developed-by: Ben Cheatham <benjamin.cheatham@amd.com>
Signed-off-by: Ben Cheatham <benjamin.cheatham@amd.com>
Reviewed-by: Tony Luck <tony.luck@intel.com>
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
(cherry picked from commit 87386ee83dc2b241eab69239f9cc82fa7fb4171c)

This commit is not a pure cherry-pick and had to be modified to fix a compile
error because we are still using -std=gnu89 and the upstream kernel has moved
on to -std=gnu11

Reworked the upstream commit to fix the following compile error by declaring
the 'pos' variable at the beginning of the function.

drivers/acpi/apei/einj.c: In function 'available_error_type_show':
drivers/acpi/apei/einj.c:591:9: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
  591 |         for (int pos = 0; pos < ARRAY_SIZE(einj_error_type_string); pos++)
      |         ^~~
drivers/acpi/apei/einj.c:591:9: note: use option '-std=c99', '-std=gnu99', '-std=c11' or '-std=gnu11' to compile your code

Orabug: 36812907

Signed-off-by: Thomas Tai <thomas.tai@oracle.com>
Reviewed-by: Henry Willard <henry.willard@oracle.com>
Signed-off-by: Brian Maly <brian.maly@oracle.com>