crypto: qat - add CRYPTO_AES to Kconfig dependencies
This patch includes a missing dependency (CRYPTO_AES) which may
lead to an "undefined reference to `aes_expandkey'" linking error.

Fixes: 5106dfeaeabe ("crypto: qat - add AES-XTS support for QAT GEN4 devices")
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Marco Chiappero <marco.chiappero@intel.com>
Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>

(cherry picked from commit c0e583ab2016de8dedfb73934d4c4e8ff5bd896c)

Orabug: 33440215

Signed-off-by: Thomas Tai <thomas.tai@oracle.com>
Reviewed-by: Henry Willard <henry.willard@oracle.com>
Signed-off-by: Brian Maly <brian.maly@oracle.com>