Nvme: fix build error
error: implicit declaration of function 'nvme_identify'
which is introduced by b4145035630715ee821528f209f098

Orabug: 22620486
Signed-off-by: Jason Luo <zhangqing.luo@oracle.com>