power: reset: pwr-mlxbf: add missing include
Add missing include for devm_work_autocancel to fix build error:

drivers/power/reset/pwr-mlxbf.c: In function 'pwr_mlxbf_probe':
drivers/power/reset/pwr-mlxbf.c:67:15: error: implicit declaration of function 'devm_work_autocancel' [-Werror=implicit-function-declaration]
   67 |         err = devm_work_autocancel(dev, &priv->send_work, pwr_mlxbf_send_work);
      |               ^~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Fixes: a4c0094fcf76 ("power: reset: pwr-mlxbf: add BlueField SoC power control driver")
Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Asmaa Mnebhi <asmaa@nvidia.com>
Signed-off-by: Sebastian Reichel <sebastian.reichel@collabora.com>

Orabug: 35290196

(cherry picked from commit a5a3d94fc4edecb894bc79810aea511ff9261c09)
cherry-pick-repo=kernel/git/torvalds/linux.git
unmodified-from-upstream: a5a3d94fc4edecb894bc79810aea511ff9261c09

Signed-off-by: Mikhael Goikhman <migo@nvidia.com>
Signed-off-by: Qing Huang <qing.huang@oracle.com>
Reviewed-by: Devesh Sharma <devesh.s.sharma@oracle.com>