KVM: SVM: fix build error when CONFIG_HYPERV is unset
UEK7 build fails when CONFIG_HYPERV is not set

Error message:
arch/x86/kvm/svm/svm.c: In function ‘svm_hardware_setup’:
arch/x86/kvm/svm/svm.c:1156:60: error: ‘svm_x86_ops’ undeclared (first use in this function); did you mean ‘kvm_x86_ops’?
 1156 |         enable_apicv = avic = avic && avic_hardware_setup(&svm_x86_ops);
      |                                                            ^~~~~~~~~~~
      |                                                            kvm_x86_ops
arch/x86/kvm/svm/svm.c:1156:60: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [scripts/Makefile.build:288: arch/x86/kvm/svm/svm.o] Error 1
make[1]: *** [scripts/Makefile.build:551: arch/x86/kvm] Error 2
make: *** [Makefile:1988: arch/x86] Error 2

Orabug: 36508934
Fixes: b80fd5ae925a ("KVM: SVM: Detect X2APIC virtualization (x2AVIC)
support")

Reviewed-by: Boris Ostrovsky <boris.ostrovsky@oracle.com>
Signed-off-by: Simran Singh <simran.p.singh@oracle.com>
Signed-off-by: Vijayendra Suman <vijayendra.suman@oracle.com>