mlx5: prevent 64bit divide
mlx5_tout_ms() returns a u64, we can't directly divide it.
This is not a problem here, @timeout which is the value
that actually matters here is already a ulong, so this
implies storing return value of mlx5_tout_ms() on a ulong
should be fine.

This fixes:

  ERROR: modpost: "__udivdi3" [drivers/net/ethernet/mellanox/mlx5/core/mlx5_core.ko] undefined!

Fixes: 32def4120e48 ("net/mlx5: Read timeout values from DTOR")
Link: https://lore.kernel.org/r/20211018172608.1069754-1-kuba@kernel.org
Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Orabug: 34481188

(cherry picked from commit ac6b7e0d9679db908d92fb96605d1ce01e8173d4)
cherry-pick-repo=kernel/git/torvalds/linux.git
unmodified-from-upstream: ac6b7e0d9679db908d92fb96605d1ce01e8173d4

Signed-off-by: Mikhael Goikhman <migo@nvidia.com>
Signed-off-by: Qing Huang <qing.huang@oracle.com>
Reviewed-by: Sharath Srinivasan <sharath.srinivasan@oracle.com>
(cherry picked from commit c8500a774debe2d9aaaca0a6f1043cee9320670d)
Signed-off-by: Jack Vogel <jack.vogel@oracle.com>