net/mlx5: Fix format-security build warnings
Treat the string as an argument to avoid this.

drivers/net/ethernet/mellanox/mlx5/core/pci_irq.c:482:5:
error: format string is not a string literal (potentially insecure)
                         name);
                         ^~~~
drivers/net/ethernet/mellanox/mlx5/core/en_stats.c:2079:4:
error: format string is not a string literal (potentially insecure)
                        ptp_ch_stats_desc[i].format);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>
Reviewed-by: Shay Drory <shayd@nvidia.com>
Reviewed-by: Moshe Shemesh <moshe@nvidia.com>

Orabug: 34481188

(cherry picked from commit aef0f8c67d752ed68cc18582711ac6accf0ad9b6)
cherry-pick-repo=kernel/git/torvalds/linux.git
unmodified-from-upstream: aef0f8c67d752ed68cc18582711ac6accf0ad9b6

Signed-off-by: Mikhael Goikhman <migo@nvidia.com>
Signed-off-by: Qing Huang <qing.huang@oracle.com>
Reviewed-by: William Kucharski <william.kucharski@oracle.com>
Reviewed-by: Devesh Sharma <devesh.s.sharma@oracle.com>
(cherry picked from commit 314e34980cdfd57310d7d523a7dea905bb3c7d6e)
Signed-off-by: Jack Vogel <jack.vogel@oracle.com>