RDS: IB: Fix the build error in previous commit dfbdf6c626
Commit dfbdf6c626ee ("RDS: IB: skip rx/tx work when destroying
connection")' using atomic api which doesn't exit which lead
to build error.

net/rds/ib_cm.c:1319: error: implicit declaration of function
‘smp_mb__after_atomic_inc’

Fix it.

Orabug: 24395789

Signed-off-by: Santosh Shilimkar <santosh.shilimkar@oracle.com>