memcg: add folio_memcg_charged() stub for !memcg
Kernel build fails with following error, when compiled with
CONFIG_MEMCG=n:

  CC      mm/huge_memory.o
In file included from ./arch/x86/include/asm/bug.h:100,
                 from ./include/linux/bug.h:5,
                 from ./include/linux/mmdebug.h:5,
                 from ./include/linux/mm.h:6,
                 from mm/huge_memory.c:8:
mm/huge_memory.c: In function ‘__folio_unqueue_deferred_split’:
mm/huge_memory.c:3725:42: error: implicit declaration of function ‘folio_memcg_charged’; did you mean ‘folio_memcg_check’?] [-Werror=implicit-function-declaration]
 3725 |  WARN_ON_ONCE(!mem_cgroup_disabled() && !folio_memcg_charged(folio));
      |                                          ^~~~~~~~~~~~~~~~~~~
./include/asm-generic/bug.h:111:25: note: in definition of macro ‘WARN_ON_ONCE’
  111 |  int __ret_warn_on = !!(condition);   \
      |                         ^~~~~~~~~
cc1: all warnings being treated as errors

It was introduced by commit 068c4ac41b83 ("mm: thp: replace
folio_memcg() with folio_memcg_charged()"), fix the build failure by
adding folio_memcg_charged() stub for !memcg builds.

Orabug: 38002245

Fixes: commit 068c4ac41b83 ("mm: thp: replace folio_memcg() with folio_memcg_charged()")
Reviewed-by: Harry Yoo <harry.yoo@oracle.com>
Signed-off-by: Kamalesh Babulal <kamalesh.babulal@oracle.com>
Signed-off-by: Harry Yoo <harry.yoo@oracle.com>