MIPS: Fix build error for mips ARCH_ATOMIC
ARCH_ATOMIC expects the definitions to be prefixed with 'arch_'.  Build fails
with following errors:

In file included from ./include/linux/atomic.h:82,
                 from ./include/linux/cpumask.h:13,
                 from ./include/linux/smp.h:13,
                 from ./arch/mips/include/asm/cpu-type.h:12,
                 from ./arch/mips/include/asm/timex.h:19,
                 from ./include/linux/timex.h:67,
                 from ./include/linux/time32.h:13,
                 from ./include/linux/time.h:60,
                 from ./include/linux/compat.h:10,
                 from arch/mips/kernel/asm-offsets.c:12:
./include/linux/atomic/atomic-instrumented.h:631:1: error: conflicting types for ‘atomic64_add’; have ‘void(s64,  atomic64_t *)’ {aka ‘void(long long int,  atomic64_t *)’}
  631 | atomic64_add(s64 i, atomic64_t *v)
      | ^~~~~~~~~~~~
In file included from ./include/linux/atomic.h:7,
                 from ./include/linux/cpumask.h:13,
                 from ./include/linux/smp.h:13,
                 from ./arch/mips/include/asm/cpu-type.h:12,
                 from ./arch/mips/include/asm/timex.h:19,
                 from ./include/linux/timex.h:67,
                 from ./include/linux/time32.h:13,
                 from ./include/linux/time.h:60,
                 from ./include/linux/compat.h:10,
                 from arch/mips/kernel/asm-offsets.c:12:
./arch/mips/include/asm/atomic.h:415:20: note: previous definition of ‘atomic64_add’ with type ‘void(long int,  atomic64_t *)’
  415 | static inline void atomic64_add(long i, atomic64_t *v)

Orabug: 38846771

Signed-off-by: Vijay Kumar <vijay.ac.kumar@oracle.com>
Reviewed-by: Dave Kleikamp <dave.kleikamp@oracle.com>
Signed-off-by: Vijayendra Suman <vijayendra.suman@oracle.com>