MIPS: OCTEON: Use current_cpu_type() for CPU model check.
Replace OCTEON_IS_OCTEON2() and OCTEON_IS_OCTEON3() with appropriate
current_cpu_type().

Resolving merge conflicts in arch/mips/cavium-octeon/dma-octeon.c manually as
git apply throws error:
error: short SHA1 c64bd87 is ambiguous.
error: repository lacks the necessary blob to fall back on 3-way merge.

Signed-off-by: Chandrakala Chavva <cchavva@caviumnetworks.com>
Signed-off-by: Anushka Singh <anushka.singh1@wipro.com>

Orabug: 34483890

Signed-off-by: Dave Kleikamp <dave.kleikamp@oracle.com>
Reviewed-by: Brian Maly <brian.maly@oracle.com>
Signed-off-by: Brian Maly <brian.maly@oracle.com>