uapi: fix linux/rds.h userspace compilation error
On the kernel side, sockaddr_storage is #define'd to
__kernel_sockaddr_storage.  Replacing struct sockaddr_storage with
struct __kernel_sockaddr_storage defined by <linux/socket.h> fixes
the following linux/rds.h userspace compilation error:

/usr/include/linux/rds.h:226:26: error: field 'dest_addr' has incomplete type
  struct sockaddr_storage dest_addr;

Signed-off-by: Dmitry V. Levin <ldv@altlinux.org>
Signed-off-by: David S. Miller <davem@davemloft.net>

Orabug: 34710962

(cherry picked from commit 1786dbf3702e33ce3afd2d3dbe630bd04b1d2e58)
cherry-pick-repo=kernel/git/torvalds/linux.git

Conflicts:
        include/uapi/linux/rds.h

Conflicts due to context differences.

Signed-off-by: Mark Haywood <mark.haywood@oracle.com>
Reviewed-by: Alan Maguire <alan.maguire@oracle.com>
Signed-off-by: Saeed Mirzamohammadi <saeed.mirzamohammadi@oracle.com>