IB/core: Introducing /sys/class/infiniband_verbs/uek_abi_version
In UEK4, both Infiniband verbs CMD_FLUSH_RELAXED_MR and EX_CMD_DESTROY_FLOW
were assigned id #50.
Even though the extended command set comes along with its own flag, some
functions (e.g. verify_command_mask from uverbs_main.c) purely go by
command ID, and end up not handling one of those two commands properly.
This was probably an oversight.

Hence in UEK5, the RELAXED_MR group of Oracle-specific Infiniband commands
were moved to start with id #43 (instead of #48 in UEK4).

User-space library libibverbs needs to deal with this incompatibility,
and instead of detecting which version of UEK is running, e.g.:

+ is_uek4_or_older_linux =
+ ( linux_version < 4 ||
+   ( linux_version == 4 && linux_patchlevel <= 1 )) &&
+ ( strstr(cp, ".el6uek.") ||
+   strstr(cp, ".el7uek."));

It is better to have the UEK5 kernel expose an Oracle ABI version file
(e.g. /sys/class/infiniband_verbs/uek_abi_version) to allow libibverbs to
tell which ABI to use.

And this uek_abi_version number can be incremented in the future in order
to handle other incompatibilities without similar hacks like the one above.

Orabug: 27959252

Signed-off-by: Gerd Rausch <gerd.rausch@oracle.com>
Reviewed-by: Shannon Nelson <shannon.nelson@oracle.com>

Orabug: 30833443

UEK5 => UEK6

(cherry picked from commit 7360df11fdede3c62817e63e741fc14896ffceb0)
cherry-pick-repo=UEK/production/linux-uek.git

Conflicts:
	drivers/infiniband/core/uverbs_main.c

Signed-off-by: Qing Huang <qing.huang@oracle.com>
Reviewed-by: Sudhakar Dindukurti <sudhakar.dindukurti@oracle.com>
Signed-off-by: Aron Silverton <aron.silverton@oracle.com>

Orabug: 30833580

UEK6 => LUCI

(cherry picked from commit 771659dbdfe612cdff03b23f02eb58d0b8840641)
cherry-pick-repo=UEK/production/linux-uek.git

Conflicts:
	drivers/infiniband/core/uverbs_main.c

Minor conflict due to difference in context (ib_uverbs_add_one returns
int) were resolved manually.

Signed-off-by: Sharath Srinivasan <sharath.srinivasan@oracle.com>
Reviewed-by: Qing Huang <qing.huang@oracle.com>
Signed-off-by: Aron Silverton <aron.silverton@oracle.com

Orabug: 37346979

LUCI => UEK8

Conflicts:
	drivers/infiniband/core/uverbs_main.c

Fix compile err: "drivers/infiniband/core/uverbs_main.c:1290:33:
error: incompatible type for argument 1 of 'class_create_file'"

caused due to upstream commit:
64917f4c35b3 ("RDMA: Make all 'class' structures const")

i.e. fix by passing "&uverbs_class" as arg1 to class_create_file().

Signed-off-by: Sharath Srinivasan <sharath.srinivasan@oracle.com>
Reviewed-by: Gerd Rausch <gerd.rausch@oracle.com>