mm: memcontrol: fix a build error on CONFIG_MEMCG=n
Commit 4717687c1a43 ("mm: memcontrol: make all the callers of
{folio,page}_memcg() safe") mistakenly defined
get_mem_cgroup_from_folio() twice when CONFIG_MEMCG is not set.

This appears to be a mistake during rebase, as a recent commit
f77f0c7514789 ("mm,memcg: provide per-cgroup counters for NUMA balancing
operations") adds get_mem_cgroup_from_folio() to
include/linux/memcontrol.h.

In the mean time, because get_mem_cgroup_from_folio() is an inline
function in include/linux/memcontrol.h, remove unnecessary function
declaration after function definition.

This fixes the build error on CONFIG_MEMCG=n:
    $ make -j$(nproc) bzImage

    DESCEND objtool
    INSTALL libsubcmd_headers
    UPD     include/config/kernel.release
    UPD     include/generated/utsrelease.h
    CC      arch/x86/kernel/asm-offsets.s
  In file included from ./include/linux/swap.h:10,
                   from ./include/linux/suspend.h:5,
                   from arch/x86/kernel/asm-offsets.c:14:
  ./include/linux/memcontrol.h:1309:34: error: redefinition of ‘get_mem_cgroup_from_folio’
   1309 | static inline struct mem_cgroup *get_mem_cgroup_from_folio(struct folio *folio)
        |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
  ./include/linux/memcontrol.h:1136:34: note: previous definition of ‘get_mem_cgroup_from_folio’ with type ‘struct mem_cgroup *(stru’
   1136 | static inline struct mem_cgroup *get_mem_cgroup_from_folio(struct folio *folio)
        |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
  make[2]: *** [scripts/Makefile.build:102: arch/x86/kernel/asm-offsets.s] Error 1
  make[1]: *** [/home/hyeyoo/linux-uek/Makefile:1229: prepare0] Error 2
  make: *** [Makefile:226: __sub-make] Error 2

Orabug: 38002245

Fixes: commit 4717687c1a43 ("mm: memcontrol: make all the callers of {folio,page}_memcg() safe")
Reviewed-by: Imran Khan <imran.f.khan@oracle.com>
Reviewed-by: Kamalesh Babulal <kamalesh.babulal@oracle.com>
Signed-off-by: Harry Yoo <harry.yoo@oracle.com>