LTS version: v5.15.185
Conflict commit
1686594d7285 coredump: hand a pidfd to the usermode coredump helper
dcbee1061a46 perf/arm-cmn: Initialise cmn->cpu earlier

Skipped commit
1a426abdf1c8 padata: do not leak refcount in reorder_work
ff887e77b777 Revert "drm/amd: Keep display off while going into S4"
5dcdbb69aa3a memcg: always call cond_resched() after fn()
5492aaea844e x86/its: Fix undefined reference to cpu_wants_rethunk_at()
ec180b032459 bridge: netfilter: Fix forwarding of fragmented packets

KABI Error:
1686594d7285 coredump: hand a pidfd to the usermode coredump helper
KABI violation in include/linux/binfmts.h corrected with EXTEND
commit adds struct pid *pid, Extended *pid withen UEK_KABI_EXTEND

Signed-off-by: Vijayendra Suman <vijayendra.suman@oracle.com>
Reviewed-by: Brian Maly <brian.maly@oracle.com>