iommu/amd: Fix compile error for unused function
Recent changes introduced a compile error:

drivers/iommu/amd/iommu.c:1285:13: error: ‘iommu_flush_irt_and_complete’ defined but not used [-Werror=unused-function]
 1285 | static void iommu_flush_irt_and_complete(struct amd_iommu *iommu, u16 devid)
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

This happens with defconfig-x86_64 because AMD IOMMU is enabled but
CONFIG_IRQ_REMAP is disabled. Move the function under #ifdef
CONFIG_IRQ_REMAP to fix the error.

Signed-off-by: Joerg Roedel <jroedel@suse.de>
(cherry picked from commit 1ce018df87640adb139c8418785ad3b6e4376bd3)
cherry-pick-repo=git://git.kernel.org/pub/scm/linux/kernel/git/joro/iommu.git

Orabug: 35070061

Suggested-by: Joao Martins <joao.m.martins@oracle.com>
Signed-off-by: Alejandro Jimenez <alejandro.j.jimenez@oracle.com>
Reviewed-by: Joao Martins <joao.m.martins@oracle.com>

Conflicts:
	drivers/iommu/amd_iommu.c
UEK does not backport:
bccc37a8a2fb ("iommu/amd: Improving Interrupt Remapping Table Invalidation")
which modifies iommu_flush_irt_and_complete(). Trivial resolution.

Signed-off-by: Brian Maly <brian.maly@oracle.com>