x86/its: Build fails with CONFIG_MITIGATION_ITS=n
If the build has ITS mitigation disabled (CONFIG_MITIGATION_ITS=n)
then it fails:

  CC      arch/x86/kernel/alternative.o
  arch/x86/kernel/alternative.c:789:13: error: ‘cpu_wants_indirect_its_thunk_at’
  defined but not used [-Werror=unused-function]
  789 | static bool cpu_wants_indirect_its_thunk_at(unsigned long addr, int reg)
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Orabug: 38756944
Signed-off-by: Alexandre Chartre <alexandre.chartre@oracle.com>
Reviewed-by: Boris Ostrovsky <boris.ostrovsky@oracle.com>