mlxsw: spectrum_flower: Make vlan_id limitation more specific
Spectrum ASICs do not support matching of VLAN ID at egress.
Currently, mlxsw driver forbids matching of all VLAN related fields at
egress, which is too strict check.

For example, the following filter is not supported by the driver:
$ tc filter add dev swpX egress protocol 802.1q pref 1 handle 101 flower
vlan_ethtype ipv4 src_ip .. dst_ip .. skip_sw action pass
Error: mlxsw_spectrum: vlan_id key is not supported on egress.
We have an error talking to the kernel

The filter above does not match on VLAN ID, but is bounced anyway.

Make the check more specific, forbid only matching of 'vlan_id' at egress.

Signed-off-by: Amit Cohen <amcohen@nvidia.com>
Reviewed-by: Petr Machata <petrm@nvidia.com>
Signed-off-by: Jakub Kicinski <kuba@kernel.org>

Orabug: 34481188

(cherry picked from commit 70ec72d5b6c25822184f7adf9ec3ba207138e7ff)
cherry-pick-repo=kernel/git/torvalds/linux.git
unmodified-from-upstream: 70ec72d5b6c25822184f7adf9ec3ba207138e7ff

Signed-off-by: Mikhael Goikhman <migo@nvidia.com>
Signed-off-by: Qing Huang <qing.huang@oracle.com>
Reviewed-by: William Kucharski <william.kucharski@oracle.com>
Reviewed-by: Devesh Sharma <devesh.s.sharma@oracle.com>
(cherry picked from commit 8a0c8903afaa6aca3a3cba6d9b754120ed94d228)
Signed-off-by: Jack Vogel <jack.vogel@oracle.com>