uapi: fix linux/rds.h userspace compilation error
On the kernel side, sockaddr_storage is #define'd to
__kernel_sockaddr_storage.  Replacing struct sockaddr_storage with
struct __kernel_sockaddr_storage defined by <linux/socket.h> fixes
the following linux/rds.h userspace compilation error:

/usr/include/linux/rds.h:226:26: error: field 'dest_addr' has incomplete type
  struct sockaddr_storage dest_addr;

Signed-off-by: Dmitry V. Levin <ldv@altlinux.org>
Signed-off-by: David S. Miller <davem@davemloft.net>

Orabug: 32967640

(cherry picked from commit 1786dbf3702e33ce3afd2d3dbe630bd04b1d2e58)
cherry-pick-repo=linux/kernel/git/torvalds/linux.git

Conflicts:
	include/uapi/linux/rds.h

Conflicts due to context differences.

Signed-off-by: Ka-Cheong Poon <ka-cheong.poon@oracle.com>
Acked-by: Santosh Shilimkar <santosh.shhilimkar@oracle.com>
Reviewed-by: Håkon Bugge <haakon.bugge@oracle.com>
(cherry picked from commit 4f5d10857e4f7b19f03a61da256bae3b65058feb)
Signed-off-by: Jack Vogel <jack.vogel@oracle.com>

Orabug: 33590097

UEK6 => UEK7

(cherry picked from commit c7dcdf91346fa660555efa1508536e546aa03df6)
cherry-pick-repo=UEK/production/linux-uek.git

Signed-off-by: Gerd Rausch <gerd.rausch@oracle.com>
Reviewed-by: William Kucharski <william.kucharski@oracle.com>

Orabug: 33590087

UEK7 => LUCI

(cherry picked from commit 2bf733e7b30483cab959edeb96539b3942bf9087)
cherry-pick-repo=UEK/production/linux-uek.git

Signed-off-by: Gerd Rausch <gerd.rausch@oracle.com>
Reviewed-by: William Kucharski <william.kucharski@oracle.com>