psi-pressure-stall-information-for-cpu-memory-and-io-fix-4
Hi Randy,

Thanks for the report.

On Wed, Sep 12, 2018 at 05:45:08PM -0700, Randy Dunlap wrote:
> Multiple build errors when CONFIG_SMP is not set: (this is on i386 fwiw)
>
> in the psi (pressure) patches, I guess:
>
> In file included from ../kernel/sched/sched.h:1367:0,
>                  from ../kernel/sched/core.c:8:
> ../kernel/sched/stats.h: In function 'psi_task_tick':
> ../kernel/sched/stats.h:135:33: error: 'struct rq' has no member named 'cpu'
>    psi_memstall_tick(rq->curr, rq->cpu);

This needs to use the SMP/UP config-aware accessor.

Link: http://lkml.kernel.org/r/20180913014222.GA2370@cmpxchg.org
Signed-off-by: Johannes Weiner <hannes@cmpxchg.org>
Reported-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
(cherry picked from commit c3e29be61e32d54a880e1475f04c1a35a4c5b4c9)

Orabug: 28813459

Signed-off-by: Tom Hromatka <tom.hromatka@oracle.com>
Reviewed-by: Darren Kenny <darren.kenny@oracle.com>