uek: kabi: use u64 for uek_reserved
The following error is observed when use UEK_KABI_USE in task_struct

In file included from ./arch/x86/include/asm/processor.h:6,
from ./arch/x86/include/asm/timex.h:5,
from ./include/linux/timex.h:67,
from ./include/linux/time32.h:13,
from ./include/linux/time.h:60,
             from arch/x86/entry/vdso/vdso32/../vclock_gettime.c:11,
from arch/x86/entry/vdso/vdso32/vclock_gettime.c:4:
./include/linux/uek_kabi.h:200:17: error: static assertion failed: "include/linux/sched.h:1590: u64 new_member
is larger than unsigned long uek_reserved3. Disable CONFIG_UEK_KABI_SIZE_ALIGN_CHECKS if debugging."
200 | _Static_assert(sizeof(struct{_new;}) <= sizeof(struct{_orig;}), \
| ^~~~~~~~~~~~~~
./include/linux/uek_kabi.h:224:17: note: in expansion of macro â€˜__UEK_KABI_CHECK_SIZE_ALIGNâ€™
224 | __UEK_KABI_CHECK_SIZE_ALIGN(_orig, _new); \
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/uek_kabi.h:247:49: note: in expansion of macro â€˜_UEK_KABI_REPLACEâ€™
247 | # define UEK_KABI_REPLACE(_orig, _new) _UEK_KABI_REPLACE(_orig, _new);
| ^~~~~~~~~~~~~~~~~
./include/linux/uek_kabi.h:261:41: note: in expansion of macro â€˜UEK_KABI_REPLACEâ€™
261 | # define UEK_KABI_USE(n, _new) UEK_KABI_REPLACE(_UEK_KABI_RESERVE(n), _new)
| ^~~~~~~~~~~~~~~~
./include/linux/sched.h:1590:9: note: in expansion of macro â€˜UEK_KABI_USEâ€™
1590 | UEK_KABI_USE(3, u64 new_memeber);
| ^~~~~~~~~~~~
make[5]: *** [scripts/Makefile.build:229: arch/x86/entry/vdso/vdso32/vclock_gettime.o] Error 1

The uek_reserve field is an unsigned long, which is 4 bytes in a 32-bit environment and
8 bytes in a 64-bit environment. This difference can trigger a size/alignment check
failure when that space is used for a u64 in the vDSO “fake” 32-bit env.
Use u64 here to enforce the reserve space to 8 bytes under any system.

Orabug: 39089314

Signed-off-by: Yifei Liu <yifei.l.liu@oracle.com>
Reviewed-by: Jack Vogel <jack.vogel@oracle.com>