perf/x86/intel/uncore: Fix the build on !CONFIG_PHYS_ADDR_T_64BIT
'val2' is unused if !CONFIG_PHYS_ADDR_T_64BIT:

  arch/x86/events/intel/uncore_discovery.c:213:18: error: unused variable ‘val2’ [-Werror=unused-variable]

Signed-off-by: Ingo Molnar <mingo@kernel.org>
(cherry picked from commit 02a08d78f5c429c7dc8e5b9417b4efb518b3d041)

Pulled from: https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git

Orabug: 34100359, 34100343

Signed-off-by: John Donnelly <john.p.donnelly@oracle.com>
Reviewed-by: Jack Vogel <jack.vogel@oracle.com>