xsigo: add prefix xve/xsvnic with gro and __path_find
The similar name function "__path_find" defined by xve_main.c and
ipoib_maini.c, is causing problems for the built-in module.
Replace "__path_find" with "__xve_path_find" to resolve this issue.

Similar to this,the modules xve and xsvnic define the global variables gro.
In the xve module, replace gro with xve_gro, and in the xsvnic module,
replace gro with xsvnic_gro.

UEK6-U3 syzkaller build error
-----------------------------
ld: drivers/infiniband/ulp/xsigo/xve/xve_main.o: in function `__path_find':

/extra1/linux-UEK6U3/drivers/infiniband/ulp/xsigo/xve/xve_main.c:389: multiple definition of `__path_find'; drivers/infiniband/ulp/ipoib/ipoib_main.o:/extra1/linux-UEK6U3/drivers/infiniband/ulp/ipoib/ipoib_main.c:591: first defined here

ld: drivers/infiniband/ulp/xsigo/xve/xve_main.o:/extra1/linux-UEK6U3/drivers/infiniband/ulp/xsigo/xve/xve_main.c:70: multiple definition of `gro'; drivers/infiniband/ulp/xsigo/xsvnic/xsvnic_main.o:/extra1/linux-UEK6U3/drivers/infiniband/ulp/xsigo/xsvnic/xsvnic_main.c:70: first defined here

make: *** [Makefile:1132: vmlinux] Error 1

-----------------------------

Orabug: 37089693

Signed-off-by: Alok Tiwari <alok.a.tiwari@oracle.com>
Reviewed-by: George Kennedy <george.kennedy@oracle.com>
Signed-off-by: Sherry Yang <sherry.yang@oracle.com>