rds/ib: move rds_ib_clear_irq_miss() to .h file
Commit "rds/ib: recover rds connection from interrupt loss scenario"
broke the aarch64 build with following error -

BUILDSTDERR: net/rds/ib_cm.c: In function 'rds_ib_tasklet_fn_send':
BUILDSTDERR: net/rds/ib.h:720:13: error: inlining failed in call to
	always_inline 'rds_ib_clear_irq_miss': function body not available
BUILDSTDERR:  inline void rds_ib_clear_irq_miss(struct rds_ib_connection

Fix this by moving the function definition to header file

Orabug: 33044344

Fixes: c37c2b9f8b55 ("rds/ib: recover rds connection from interrupt loss
scenario")

Signed-off-by: Manjunath Patil <manjunath.b.patil@oracle.com>
Reviewed-by: Håkon Bugge <haakon.bugge@oracle.com>

Orabug: 33590097

UEK6 => UEK7

(cherry picked from commit c3119a4b464172b63730540e72958fe826fe3c7a)
cherry-pick-repo=UEK/production/linux-uek.git

Signed-off-by: Gerd Rausch <gerd.rausch@oracle.com>
Reviewed-by: William Kucharski <william.kucharski@oracle.com>

Orabug: 37347036

UEK7 => LUCI => UEK8

(cherry picked from commit af98ff2441edae7da866a3d996fcfc7ad8a8049f)
cherry-pick-repo=UEK/production/linux-uek.git

Signed-off-by: Gerd Rausch <gerd.rausch@oracle.com>
Reviewed-by: William Kucharski <william.kucharski@oracle.com>