sched: Fix non-CONFIG_SCHED_CORE build
Commit c0d4607eff28 ("sched: Add interface for copying core scheduling
cookie between two tasks") mistakenly put a semicolon in definition of
sched_cs_copy() when CONFIG_SCHED_CORE is not defined, resulting in
build breakage:

In file included from arch/x86/kernel/asm-offsets.c:10:
./include/linux/sched.h:2328:59: error: expected identifier or '(' before '{' token
 2328 |                                 struct task_struct *dst); { }
      |                                                           ^
./include/linux/sched.h:2327:20: warning: 'sched_cs_copy' declared 'static' but never defined [-Wunused-function]
 2327 | static inline void sched_cs_copy(struct task_struct *src,
      |                    ^~~~~~~~~~~~~
make[1]: *** [scripts/Makefile.build:121: arch/x86/kernel/asm-offsets.s]
Error 1
make: *** [Makefile:1237: prepare0] Error 2

Drop the semicolon.

Orabug: 34228424

Signed-off-by: Boris Ostrovsky <boris.ostrovsky@oracle.com>
Reviewed-by: Patrick Colp <patrick.colp@oracle.com>