mlx5: fix mlx5i_grp_sw_update_stats() stack usage
The mlx5e_sw_stats structure has grown to the point of triggering
a warning when put on the stack of a function:

mlx5/core/ipoib/ipoib.c: In function 'mlx5i_grp_sw_update_stats':
mlx5/core/ipoib/ipoib.c:136:1: error: the frame size of 1028 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]

In this case, only five of the structure members are actually set,
so it's sufficient to have those as separate local variables.
As en_rep.c uses 'struct rtnl_link_stats64' for this, just use
the same one here for consistency.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Saeed Mahameed <saeedm@nvidia.com>

Orabug: 34481188

(cherry picked from commit d2b8c7ba3c795a4ef8de48009fd13735b1a428e5)
cherry-pick-repo=kernel/git/torvalds/linux.git
unmodified-from-upstream: d2b8c7ba3c795a4ef8de48009fd13735b1a428e5

Signed-off-by: Mikhael Goikhman <migo@nvidia.com>
Signed-off-by: Qing Huang <qing.huang@oracle.com>
Reviewed-by: William Kucharski <william.kucharski@oracle.com>
Reviewed-by: Devesh Sharma <devesh.s.sharma@oracle.com>
(cherry picked from commit f8cdf9e8f1f5e451a57139a614bee18ea49b0b95)
Signed-off-by: Jack Vogel <jack.vogel@oracle.com>