octeontx2-af: Initialize 'cntr_val' to fix uninitialized symbol error
drivers/net/ethernet/marvell/octeontx2/nic/otx2_tc.c:860
otx2_tc_update_mcam_table_del_req()
error: uninitialized symbol 'cntr_val'.

Fixes: ec87f05402f5 ("octeontx2-af: Install TC filter rules in hardware based on priority")
Signed-off-by: Suman Ghosh <sumang@marvell.com>
Link: https://lore.kernel.org/r/20230727163101.2793453-1-sumang@marvell.com
Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit 222a6c42e9ef131fd20463bf95d7ce7b39bee2f8)

Orabug: 36725601

Signed-off-by: Dave Kleikamp <dave.kleikamp@oracle.com>
Reviewed-by: Brian Maly <brian.maly@oracle.com>
Reviewed-by: Tom Saeger <tom.saeger@oracle.com>
Signed-off-by: Brian Maly <brian.maly@oracle.com>