MIPS: OCTEON: Fix plat_swiotlb_setup() for OCTEON3
Resolving merge conflicts in arch/mips/cavium-octeon/dma-octeon.c
Patch applied using patch -p1 as git apply throws error
error: repository lacks the necessary blob to fall back on 3-way merge.

Signed-off-by: David Daney <david.daney@cavium.com>
Signed-off-by: Anushka Singh <anushka.singh1@wipro.com>

Orabug: 34483890

Signed-off-by: Dave Kleikamp <dave.kleikamp@oracle.com>
Reviewed-by: Brian Maly <brian.maly@oracle.com>
Signed-off-by: Brian Maly <brian.maly@oracle.com>