Revert "treewide: Replace DECLARE_TASKLET() with DECLARE_TASKLET_OLD()"
This reverts commit 5de7a4254eb2d501cbb59918a152665b29c02109 which
caused mips build failures.

kernelci.org bot reports:

arch/mips/lasat/picvue_proc.c:87:20: error: ‘pvc_display_tasklet’ undeclared
(first use in this function)
arch/mips/lasat/picvue_proc.c:42:44: error: expected ‘)’ before ‘&’ token
arch/mips/lasat/picvue_proc.c:33:13: error: ‘pvc_display’ defined but not used
[-Werror=unused-function]

Link: https://lore.kernel.org/stable/64041dda.170a0220.8cc25.79c9@mx.google.com/
Reported-by: "kernelci.org bot" <bot@kernelci.org>
Signed-off-by: Tom Saeger <tom.saeger@oracle.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
(cherry picked from commit 199197660bdd7c5b84ed50b382ed6252b6d10ccb)
Signed-off-by: Sherry Yang <sherry.yang@oracle.com>

Conflicts:
	drivers/staging/octeon/ethernet-tx.c
Ignore all changes in file drivers/staging/octeon/ethernet-tx.c, because this file
was deleted in uek6/u3 through commit 19082a01c5bc ("netdev: octeon: Move and update
octeon network driver from staging."), and consulted Dave,"The Cavium (Marvell)
drivers are completely changed in UEK6 since Marvell gives us much more recent code
than was in the v5.4 kernel. (It is even different than what they have sent upstream.)
It looks like that change is no longer relevant to the Cavium code now in UEK6."