ipoib: rfe- enable pkey and device name decoupling
The sysfs "create_child" interface creates pkey based child interface but
derives the name from parent device name and pkey value.
This makes administration difficult where pkey values can change but
policies encoded with device names do not.

We add ability to create a child interface with a user specified name and a
specified pkey with a new sysfs "create_named_child" interface (and also
add a corresponding "delete_named_child" interface).

We also add a new module api interface to query pkey from a netdevice so
any kernel users of pkey based child interfaces can query it - since with
device name decoupled from pkey, it can no longer be deduced from parsing
the device name by other kernel users.

Orabug: 19064704

Ported from UEK2 commits
a101f6037e882b1c12143416d48345fe7ea62979 and
916eb26c32082e241c22fcf8064959d697eabe2b

Signed-off-by: Mukesh Kacker <mukesh.kacker@oracle.com>
Reviewed-by: Yuval Shaia <yuval.shaia@oracle.com>
Reviewed-by: Chien-Hua Yen <chien.yen@oracle.com>
Signed-off-by: Guangyu Sun <guangyu.sun@oracle.com>

Orabug: 27383465

(cherry picked from commit f70a5ac6ed7eb212ec282fa71f2993c0e003628d)
cherry-pick-repo=linux-uek.git

Conflicts:
    drivers/infiniband/ulp/ipoib/ipoib_main.c
    drivers/infiniband/ulp/ipoib/ipoib_vlan.c

Signed-off-by: Yuval Shaia <yuval.shaia@oracle.com>
Signed-off by: Aron Silverton <aron.silverton@oracle.com>
Reviewed-by: Sudhakar Dindukurti <sudhakar.dindukurti@oracle.com>

Signed-off-by: Somasundaram Krishnasamy <somasundaram.krishnasamy@oracle.com>

Orabug: 30833819

UEK5 => UEK6

(cherry picked from commit 79f6d772f0f3eb2335f3c56a04e231457b49b138)
cherry-pick-repo=UEK/production/linux-uek.git

Conflicts:
	drivers/infiniband/ulp/ipoib/ipoib_vlan.c
	Documentation/infiniband/ipoib.rst (was .txt)

The conflicts were a result of changes made in upstream code.

Signed-off-by: Yuval Shaia <yuval.shaia@oracle.com>
Signed-off-by: Qing Huang <qing.huang@oracle.com>
Reviewed-by: Sudhakar Dindukurti <sudhakar.dindukurti@oracle.com>
Signed-off-by: Aron Silverton <aron.silverton@oracle.com>

Orabug: 30833820

UEK6 => LUCI

(cherry picked from commit 4c5226457479897172cc8401dfdcb332d5dbf660)
cherry-pick-repo=UEK/production/linux-uek.git

Conflicts:
	drivers/infiniband/ulp/ipoib/ipoib_main.c

Minor conflict due to difference in the context was resolved manually.

Signed-off-by: Sharath Srinivasan <sharath.srinivasan@oracle.com>
Reviewed-by: Qing Huang <qing.huang@oracle.com>
Signed-off-by: Aron Silverton <aron.silverton@oracle.com

Orabug: 30833820

LUCI => v6.8-rc3

Conflicts:
	drivers/infiniband/ulp/ipoib/ipoib.h

	Fix -Wmissing-prototypes build warning:

	drivers/infiniband/ulp/ipoib/ipoib_main.c:2825:1:
	warning: no previous prototype for ‘ipoib_get_netdev_pkey’
	[-Wmissing-prototypes]

	by including fn prototypes in ipoib.h for 3 functions
	introduced in this patch:
	ipoib_get_netdev_pkey(), ipoib_vlan_add_common() &
	ipoib_vlan_delete_common().

Signed-off-by: Sharath Srinivasan <sharath.srinivasan@oracle.com>
Reviewed-by: Qing Huang <qing.huang@oracle.com>

Orabug: 30833820

LUCI => v6.10-rc3

Conflicts:
	drivers/infiniband/ulp/ipoib/ipoib_vlan.c

	Fix merge conflict in Hunk#3 due to upstream commit
	49ca2b2ef3d0 ("RDMA/IPoIB: Fix format truncation compilation errors")

	and update patch to include fix from commit 49ca2b2ef3d0:
	BUILD_BUG_ON(IFNAMSIZ != 16);
	snprintf(...,"%.10s.%04x",...);

Signed-off-by: Sharath Srinivasan <sharath.srinivasan@oracle.com>
Reviewed-by: Qing Huang <qing.huang@oracle.com>