ktask: export symbol for use in module definitions
Prior to this commit, changing kernel config from:
CONFIG_VFIO_IOMMU_TYPE1=y
to
CONFIG_VFIO_IOMMU_TYPE1=m

Would cause compile errors:
ERROR: "__ktask_run_numa" [drivers/vfio/vfio_iommu_type1.ko] undefined!
ERROR: "ktask_iter_range" [drivers/vfio/vfio_iommu_type1.ko] undefined!

Use EXPORT_SYMBOL to support case where modules are using ktask.

Orabug: 30484033

Signed-off-by: Tom Saeger <tom.saeger@oracle.com>
Signed-off-by: Dave Kleikamp <dave.kleikamp@oracle.com>
Reviewed-by: Henry Willard <henry.willard@oracle.com>