crypto: arm/curve25519 - include <linux/scatterlist.h>
commit 6779d0e6b0fe193ab3010ea201782ca6f75a3862 upstream.

Building ARM allmodconfig leads to the following warnings:

arch/arm/crypto/curve25519-glue.c:73:12: error: implicit declaration of function 'sg_copy_to_buffer' [-Werror=implicit-function-declaration]
arch/arm/crypto/curve25519-glue.c:74:9: error: implicit declaration of function 'sg_nents_for_len' [-Werror=implicit-function-declaration]
arch/arm/crypto/curve25519-glue.c:88:11: error: implicit declaration of function 'sg_copy_from_buffer' [-Werror=implicit-function-declaration]

Include <linux/scatterlist.h> to fix such warnings

Reported-by: Olof's autobuilder <build@lixom.net>
Fixes: 0c3dc787a62a ("crypto: algapi - Remove skbuff.h inclusion")
Signed-off-by: Fabio Estevam <festevam@gmail.com>
Acked-by: Ard Biesheuvel <ardb@kernel.org>
Acked-by: Jason A. Donenfeld <Jason@zx2c4.com>
Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>
Signed-off-by: Jason A. Donenfeld <Jason@zx2c4.com>

Orabug: 32013736

(cherry picked from commit 6779d0e6b0fe193ab3010ea201782ca6f75a3862)
cherry-pick-repo=https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/
unmodified-from-upstream: 6779d0e6b0fe193ab3010ea201782ca6f75a3862

Signed-off-by: William Kucharski <william.kucharski@oracle.com>
Reviewed-by: Sharon Liu <sharon.s.liu@oracle.com>