MIPS: OCTEON: Make PCIe work with Little Endian kernel.
Supply little-endian address bit definitions as well as set proper
endian swapping modes.

Resolving merge conflict
Using patch command to apply the patch as git apply throws error:
error: repository lacks the necessary blob to fall back on 3-way merge.

Signed-off-by: David Daney <david.daney@cavium.com>
Signed-off-by: Anushka Singh <anushka.singh1@wipro.com>

Orabug: 34483890

Signed-off-by: Dave Kleikamp <dave.kleikamp@oracle.com>
Reviewed-by: Brian Maly <brian.maly@oracle.com>
Signed-off-by: Brian Maly <brian.maly@oracle.com>