sched: replace INIT_COMPLETION with reinit_completion
For the casual device driver writer, it is hard to remember when to use
init_completion (to init a completion structure) or INIT_COMPLETION (to
*reinit* a completion structure).  Furthermore, while all other
completion functions exepct a pointer as a parameter, INIT_COMPLETION
does not.  To make it easier to remember which function to use and to
make code more readable, introduce a new inline function with the proper
name and consistent argument type.  Update the kernel-doc for
init_completion while we are here.

Signed-off-by: Wolfram Sang <wsa@the-dreams.de>
Acked-by: Linus Walleij <linus.walleij@linaro.org> (personally at LCE13)
Cc: Ingo Molnar <mingo@kernel.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>

Orabug: 21258923

Fix error drivers/hv/hv_balloon.c:1265: error: implicit declaration of function
'reinit_completion' which results from upstream commit
ab3de22bb4a3d4bda2d0ec8bebcb76a40f1cbf9b

(cherry picked from commit c32f74ab2872994bc8336ed367313da3139350ca)
Signed-off-by: Jason Luo <zhangqing.luo@oracle.com>
Signed-off-by: Guangyu Sun <guangyu.sun@oracle.com>